title: Aviation Conference Deadlines
description: Countdowns to Aviation conference deadlines.
author: Seokbin Yoon

domain: "seokbinyoon96.github.io"
baseurl: "/aviation-deadlines"

github_username: seokbinyoon96
github_repo: aviation-deadlines
#ga_id: UA-104921371-1

markdown: kramdown
